# Site settings
title: "HackKing Versailles"
email: "ping@mozzarellabs.com"
description: A web app to build a 3D-printable customized picture frame
baseurl: "/hackking" # the subpath of your site, e.g. /hackking
url: "" # the base hostname & protocol for your site
twitter_username: mozzarellabs
github_username:  tart2000

# Build settings
markdown: kramdown
